FROM microsoft/mssql-server-linux

RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y gnupg2
RUN apt-get install -y net-tools
RUN apt-get install -y netcat

ENV MSSQL_SA_PASSWORD=Passw@rd
ENV ACCEPT_EULA=Y

RUN mkdir -p /folder_for_dbs

VOLUME ["/folder_for_dbs"]

EXPOSE 1433

