FROM microsoft/mssql-server-linux

#RUN apt-get update
#RUN apt-get install -y --no-install-recommends apt-utils
#RUN apt-get install -y gnupg2
#RUN apt-get install -y net-tools
#RUN apt-get install -y netcat

ENV MSSQL_SA_PASSWORD=Passw@rd
ENV ACCEPT_EULA=Y

RUN mkdir -p /folder_for_dbs
RUN mkdir -p /folder_for_imports
ADD ./Utils/CreateDockrCourseDb.sql /folder_for_imports

VOLUME ["/folder_for_dbs"]

EXPOSE 1433

RUN /opt/mssql/bin/sqlservr & sleep 20 && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Passw@rd' -d master -i /folder_for_imports/CreateDockrCourseDb.sql && pkill sqlservr 