FROM ubuntu

RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y gnupg2
RUN apt-get install -y net-tools
RUN apt-get install -y netcat
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
RUN echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.0.list
RUN apt-get install -y mongodb
RUN mkdir -p /folder_for_dbs

VOLUME ["/folder_for_dbs"]

EXPOSE 27017
ENTRYPOINT ["/usr/bin/mongod", "--dbpath", "/folder_for_dbs", "--bind_ip_all"]
